//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dostarcza> dostarcza { get; set; }
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<Odbiorcy> Odbiorcy { get; set; }
        public virtual DbSet<potrzebny_do_produkcji> potrzebny_do_produkcji { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Składniki> Składniki { get; set; }
        public virtual DbSet<Stan_zamówienia> Stan_zamówienia { get; set; }
        public virtual DbSet<Stanowisko> Stanowisko { get; set; }
        public virtual DbSet<Wykonują> Wykonują { get; set; }
        public virtual DbSet<Zadania> Zadania { get; set; }
        public virtual DbSet<Zamówienia> Zamówienia { get; set; }
        public virtual DbSet<zawierają> zawierają { get; set; }
    }
}
