//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dostarcza
    {
        public int Id { get; set; }
        public int ID_dostawcy { get; set; }
        public int ID_składnika { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        public virtual Składniki Składniki { get; set; }
    }
}
