//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wykonują
    {
        public int Id { get; set; }
        public int ID_Pracownika { get; set; }
        public int ID_Zadania { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Zadania Zadania { get; set; }
    }
}
