//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienia()
        {
            this.zawierają = new HashSet<zawierają>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data_złożenia { get; set; }
        public System.DateTime Data_odbioru { get; set; }
        public int ID_stanu { get; set; }
        public int ID_odbiorcy { get; set; }
    
        public virtual Odbiorcy Odbiorcy { get; set; }
        public virtual Stan_zamówienia Stan_zamówienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawierają> zawierają { get; set; }
    }
}
